'use strict';

// tests for helloName
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'helloName' });

const lambdaEvent = JSON.parse(`{
  "queryStringParameters": {
    "name": "Dude"
  }
}`);

describe('helloName', () => {
  beforeAll(done => {
    // lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('responds to a stranger', () => {
    return wrapped.run({}).then(response => {
      expect(response.body).toEqual('{"message":"Hello, stranger!"}');
    });
  });

  it('responses with given querystring name', () => {
    return wrapped.run(lambdaEvent).then(response => {
      expect(response.body).toEqual('{"message":"Hello, Dude!"}');
    });
  });
});
